### ISSUE TITLE
How to create a text corpus file for custom data ?

### ISSUE THREAD

**Issue by shubhamsoulpage** [JudeLee19/HMNet-End-to-End-Abstractive-Summarization-for-Meetings#3]
How to create a text corpus for a custom data 
[Sample_transcript.txt](https://github.com/JudeLee19/HMNet-End-to-End-Abstractive-Summarization-for-Meetings/files/4999438/Sample_transcript.txt)

Just like train_corpus and test_corpus present under data folder.

**Comment by JudeLee19** [comment]
I followed "https://github.com/bearblog/CoreRank/blob/master/data/utterance_community_detection.py", when creating text corpus.

**Comment by Sperao** [comment]
> I followed "https://github.com/bearblog/CoreRank/blob/master/data/utterance_community_detection.py", when creating text corpus.

How to deal with Chinese data

**Comment by Sperao** [comment]
> 创建文本语料库时，我遵循了“ https://github.com/bearblog/CoreRank/blob/master/data/utterance_community_detection.py ”。

Can you give me the code for processing the data
